[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.28.0"
sha3 = "0.10.8"
pyo3 = "0.20.0"
hex = "0.4.3"
rlp = "0.5.2"